spring:
  datasource:
    jdbc-url: ENC(iBaJofKZjWy9NDpuNC5wd4M8i/3RyhQfgSl4f4x6tLgzYuzgBxX93kqSBHwszfzrtLGW69Wx2zG4qKIXntjF8PzU/GpLxYN6EGrmJYgg7+k=)
    username: ENC(awGg9IVxTYSRiQTrjg5LveDpEvr9XU6Qfv8P9W7zq+H3WCMxm+NE6X1JfiUXqOFh)
    password: ENC(sUlYYffIb8t7gsonvhF+aMYBv7J9Stz5/WzL15vWFkQ46w1LN1qMaQlGQBtGUpoX)
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      connectionTimeout: 60000
      idleTimeout: 120000
      maxLifetime: 360000
      minimumIdle: 10
      maximumPoolSize: 25
      leakDetectionThreshold: 90000
  jpa:
    hibernate:
      show_sql: true
      use_sql_comments: true
      format_sql: true
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    jackson:
      mapper:
        accept-case-insensitive-enums: true

logging:
  level:
    org:
      hibernate:
        type: trace
    com:
      zaxxer:
        hikari: debug