server-name: hello-propertiessss

---
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    url: ENC(buQ9hrC6Wh8MNK3yZvievf1XiZGTc8OOxnP4v4ZpZp3kXZUiam3N5lRg2TrxAmteUAX+CYe53cHZbspK/ub2lsuNpiBmk2TDL9P+xYMxLvVo+yMOu/pcDVeHlQqOdzum)
    username: ENC(WrM8tEgH/skLR/WswsS4x6rgYmB13pwAzd+vkexLsKBjrzOWxqjHhGMkxaQfKRXw)
    password: ENC(lh0Q61/C8eRNh8Iw7BE7k5Sa3lpDBkH1FivR21TPnMnNZTHZ4cu2KdBOVSF6MwoL)
    testWhileIdle: true
    validationQuery: SELECT 1
