server:
  port: 8080
  ssl:
    #keytool -genkeypair -alias vocabularyapi -keyalg RSA -keysize 4096 -storetype PKCS12 -keystore vocabulary-api.p12 -keypass <pass> -storepass <pass> -validity 3650 -dname "CN=Vocabulary Api,OU=Aaron,O=Aaron,L=Singapore,ST=Singapore,C=PH" -ext SAN=dns:localhost,ip:127.0.0.1
    #keytool -export -alias vocabularyapi -file vocabulary-api.crt -keystore vocabulary-api.p12 -storepass <pass>
    #keytool -import -alias springconfigserver -file spring-config-server.crt -keystore vocabulary-api.p12 -storepass <pass>
    enabled: true
    #client-auth: need
    key-alias: vocabularyapi
    key-store: config/keystore/vocabulary-api.p12
    key-store-type: PKCS12
    key-store-password: ENC(CZIdXEvnrFte+OCOkiTSjOSl1/enu2NCgp0r3ofhKozkBrwBLn/NVWgtpfq5BVmX)

security:
  jjwt:
    secret: ENC(bIXBnZYmyTirv2SjydfEuQKO9uEPgaifPrOPCSBoJwmHlLAlRyykIyYdkc+P0frB48mdQpAia5ASzVX+BMJ8TQDaZWr6+QJSQFCB+/ukS4noVFcJZQM+o5twPbgJhf8LSE2lgXEhpUG+t8sikoYt0w==)
    expiration: 60
  authentication:
    password: ENC(j4IrvGLp0XRKgQXYbawz+5xee+kJTJ92OcJUPMndaBNlkOjGOT8BeX6iK2cdKATw)

spring:
  webflux:
    base-path: /Vocabulary
  datasource:
    url: ENC(nGdar7UaDXvi/4mX8g1ccE1zCg6pVOIs9yjzep5O6OzcMJsDjfgSiSIRzQfuy00Ym/R0mV6qMcTf/aTsjn+nFFJ/xFwtzc4RhuytLJSecXnPf16D1GHS5PRXWRbiB7/R)
    username: ENC(7VCZ6YVdwVHlonLGbd5YBfTlrJukjvuftmN6NrbmOCYjlnf56Xwpe+JyM7LKNL/O)
    password: ENC(aKgDmLp0PwuPfa+GKcnbkZkQ4RsFQKibZQ8TClIJ7PLCDLD0krftN6RgX9m13d/U)
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      connectionTimeout: 60000
      idleTimeout: 120000
      maxLifetime: 360000
      minimumIdle: 10
      maximumPoolSize: 25
      leakDetectionThreshold: 90000
  jpa:
    hibernate:
      show_sql: false
      use_sql_comments: false
      format_sql: false
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    jackson:
      mapper:
        accept-case-insensitive-enums: true
  flyway: # Will start fresh on every docker-compose run
    enabled: true
    baseline-on-migrate: true
    schemas: my_vocabulary
    default-schema: my_vocabulary
    locations: filesystem:db/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ENC(LYmLP78qrFNRy2bbk3PKn1FLni4dq1Do53NDQZK2CYCQUQxCIse335HH05hSkMtrARcb7jIiuon4QeaAUM+5tk2OsUgrjYcus3sStTP/D+s=)

management:
  endpoints:
    web:
      exposure:
        include: refresh

logging:
  level:
    org:
      hibernate:
        type: warn
    com:
      zaxxer:
        hikari: warn